# QuTiP example: Single Quantum Gate Decompositions


## Introduction

If we need to build a circuit with a $n \times n$ quantum gate, there's no way to build a quantum circuit with just the array as an input without decomposing the  $n \times n$ array into known gates. Such a decomposition is equivalent to the $n \times n$ quantum gate within some global phase factor.

There's more than one way to decompose a $n \times n$ array which leads to a need for optimizing the decompositions by decreasing the total number of gates, keeping the number of expensive gates upto some lower bound etc. 


If there's a quantum gate $U$ acting on 1 qubit then it is a $2 \times 2 $ unitary of the following form :

\begin{equation}
U =
\begin{bmatrix}
    a       & b \\
    -b^*       & a^*  \\
\end{bmatrix}
\end{equation}

Such a unitary can be decomposed into a description of rotation matrices or rotation matrices and Pauli matrices. 

### Product of Rotation Matrices

In order to decompose above $U$ into a description of rotation matrices, we try to describe $U$ as

\begin{equation}
U =  \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_i(\beta) , \text{ }\forall \text{ }i, j \in \{ \textrm{X}, \textrm{Y}, \textrm{X}\} \text{ and } i \neq j
\end{equation}

$U$ can be decomposed as either of following :

\begin{equation}
U = \textrm{R}_Z(\alpha)  \textrm{R}_Y(\theta)  \textrm{R}_Z(\beta)
\end{equation}

\begin{equation}
U = \textrm{R}_Z(\alpha)  \textrm{R}_X(\theta)  \textrm{R}_Z(\beta)
\end{equation}

\begin{equation}
U = \textrm{R}_Y(\alpha)  \textrm{R}_X(\theta)  \textrm{R}_Y(\beta)
\end{equation}

\begin{equation}
U = \textrm{R}_Y(\alpha)  \textrm{R}_Z(\theta)  \textrm{R}_Y(\beta)
\end{equation}

\begin{equation}
U = \textrm{R}_X(\alpha)  \textrm{R}_Y(\theta)  \textrm{R}_X(\beta)
\end{equation}

\begin{equation}
U = \textrm{R}_X(\alpha)  \textrm{R}_Z(\theta)  \textrm{R}_X(\beta)
\end{equation}


In [1]:
%matplotlib inline
from IPython.display import Image
import cmath
from numpy import pi
import numpy as np
from qutip import *
from qutip_qip.operations import *
from qutip_qip.circuit import QubitCircuit, Gate
from qutip_qip.decompositions.single_decompositions import (product_of_rotation_matrices, ABC_decomposition)
from qutip_qip.decompositions.decompositions_extras import (decomposed_gates_to_circuit, matrix_of_decomposed_gates)

#### Hadamard ($\textrm{H}$) 

\begin{equation}
\textrm{H} =
\begin{bmatrix}
    \frac{1}{\sqrt{2}}      & \frac{1}{\sqrt{2}} \\
    \frac{1}{\sqrt{2}}       & \frac{-1}{\sqrt{2}}  \\
\end{bmatrix}
\end{equation}

In [2]:
num_of_qubits = 1
H = Qobj([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])


We want to decompose $\textrm{H}$ as following product :

\begin{equation}
\textrm{H} = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'

In [3]:
H_zyz_gates=product_of_rotation_matrices(H,1,'ZYZ')
H_zyz_quantum_circuit = decomposed_gates_to_circuit(H_zyz_gates, num_of_qubits)
H_zyz_quantum_circuit.png

**Note**: The input $\textrm{H}$ was multiplied by a global phase factor of $\frac{\pi}{2}$. We undo this action by multiplying the resultant gate combination by inverse of the same global phase factor.

Now, we check if the output of above matches to that of the input gate. 

In [4]:
# Check the output
H_zyz_output = matrix_of_decomposed_gates(H_zyz_quantum_circuit)
H_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

#### Pauli X ($ \sigma_x$)

\begin{equation}
\sigma_x =
\begin{bmatrix}
    0      & 1 \\
    1       & 0  \\
\end{bmatrix}
\end{equation}

We want to decompose $\sigma_x$ as following product :

\begin{equation}
\sigma_x = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'

In [5]:
sigmax = Qobj([[0,1],[1,0]])
sigmax_zyz_gates=product_of_rotation_matrices(sigmax,1,'ZYZ')
sigmax_zyz_quantum_circuit = decomposed_gates_to_circuit(sigmax_zyz_gates, num_of_qubits)
sigmax_zyz_quantum_circuit.png

In [6]:
# Check the output
sigmax_zyz_output = matrix_of_decomposed_gates(sigmax_zyz_quantum_circuit)
sigmax_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

#### Pauli Y ($ \sigma_y$)

\begin{equation}
\sigma_y =
\begin{bmatrix}
    0      & -i \\
    i       & 0  \\
\end{bmatrix}
\end{equation}

We want to decompose $\sigma_y$ as following product :

\begin{equation}
\sigma_y = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'

In [7]:
sigmay = Qobj([[0,-1j],[1j,0]])
sigmay_zyz_gates=product_of_rotation_matrices(sigmay,1,'ZYZ')
sigmay_zyz_quantum_circuit = decomposed_gates_to_circuit(sigmay_zyz_gates, num_of_qubits)
sigmay_zyz_quantum_circuit.png

In [8]:
# Check the output
sigmay_zyz_output = matrix_of_decomposed_gates(sigmay_zyz_quantum_circuit)
sigmay_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

#### Pauli Z ($ \sigma_z$)

\begin{equation}
\sigma_z =
\begin{bmatrix}
    1      & 0 \\
    0       & -1  \\
\end{bmatrix}
\end{equation}

We want to decompose $\sigma_z$ as following product :

\begin{equation}
\sigma_z = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'


In [9]:
sigmaz = Qobj([[1,0],[0,-1]])
sigmaz_zyz_gates=product_of_rotation_matrices(sigmaz,1,'ZYZ')
sigmaz_zyz_quantum_circuit = decomposed_gates_to_circuit(sigmaz_zyz_gates, num_of_qubits)
sigmaz_zyz_quantum_circuit.png

In [10]:
# Check the output
sigmaz_zyz_output = matrix_of_decomposed_gates(sigmaz_zyz_quantum_circuit)
sigmaz_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

#### Single-Qubit Rotation ($\textrm{S}$)

\begin{equation}
\textrm{S} =
\begin{bmatrix}
    1      & 0 \\
    0       & i  \\
\end{bmatrix}
\end{equation}

We want to decompose $\textrm{S}$ as following product :

\begin{equation}
\textrm{S} = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'

In [11]:
S = Qobj([[1,0],[0,1j]])
S_zyz_gates=product_of_rotation_matrices(S,1,'ZYZ')
S_zyz_quantum_circuit = decomposed_gates_to_circuit(S_zyz_gates, num_of_qubits)
S_zyz_quantum_circuit.png

In [12]:
# Check the output
S_zyz_output = matrix_of_decomposed_gates(S_zyz_quantum_circuit)
S_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+1.j 0.+0.j]
 [0.+0.j 1.+0.j]]

#### Square Root of S $\left( \textrm{T} \right)$

\begin{equation}
\textrm{S} =
\begin{bmatrix}
    1      & 0 \\
    0       & e^{\frac{i \pi}{4}}  \\
\end{bmatrix}
\end{equation}

We want to decompose $\textrm{T}$ as following product :

\begin{equation}
\textrm{T} = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'


In [13]:
T = Qobj([[1,0],[0,cmath.rect(1, np.pi/4)]])
T_zyz_gates=product_of_rotation_matrices(T,1,'ZYZ')
T_zyz_quantum_circuit = decomposed_gates_to_circuit(T_zyz_gates, num_of_qubits)
T_zyz_quantum_circuit.png

In [14]:
# Check the output
T_zyz_output = matrix_of_decomposed_gates(T_zyz_quantum_circuit)
T_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.70710678+0.70710678j  0.        +0.j        ]
 [ 0.        +0.j          0.        -1.j        ]]

#### Square Root of NOT gate $\left( \textrm{SQRTNOT} \right)$

\begin{equation}
\textrm{SQRTNOT} =
\begin{bmatrix}
    \frac{1}{\sqrt{2}}      & \frac{-i}{\sqrt{2}} \\
    \frac{-i}{\sqrt{2}}       & \frac{1}{\sqrt{2}}  \\
\end{bmatrix}
\end{equation}

We want to decompose $\textrm{SQRTNOT}$ as following product :


\begin{equation}
\textrm{SQRTNOT} = \textrm{R}_i(\alpha)  \textrm{R}_j(\theta)  \textrm{R}_k(\beta)
\end{equation}

<span style="color:red">**Note :**</span> Change input method in `product_of_rotation_matrices(..., method)` if you prefer to decompose the gate as a different combination of gates. 

Available methods : 'ZYZ', 'ZXZ','YXY', 'YZY', 'XYX', 'XZX'

In [15]:
SQRTNOT = Qobj([[1/np.sqrt(2),-1j/np.sqrt(2)],[-1j/np.sqrt(2),1/np.sqrt(2)]])
SQRTNOT_zyz_gates=product_of_rotation_matrices(SQRTNOT,1,'ZYZ')
SQRTNOT_zyz_quantum_circuit = decomposed_gates_to_circuit(SQRTNOT_zyz_gates, num_of_qubits)
SQRTNOT_zyz_quantum_circuit.png

In [16]:
# Check the output
SQRTNOT_zyz_output = matrix_of_decomposed_gates(SQRTNOT_zyz_quantum_circuit)
SQRTNOT_zyz_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.70710678+0.j          0.        +0.70710678j]
 [ 0.        +0.70710678j -0.70710678+0.j        ]]

### ABC Decomposition

In order to decompose above $U$ into a description of rotation matrices, we try to describe $U$ as

\begin{equation}
U = \textrm{AXBXC}
\end{equation}

Here, $ \textrm{A} = \textrm{R}_z(\alpha)  \textrm{R}_y \left( \frac{\theta}{2} \right)$, $\textrm{X} = \sigma_x$, 
 $ \textrm{B} = \textrm{R}_y \left( \frac{-\theta}{2} \right)  \textrm{R}_z \left( \frac{-(\alpha+\beta)}{2} \right)$, and $\textrm{C} = \textrm{R}_z \left( \frac{(-\alpha+\beta)}{2}\right)$
 
#### Hadamard ($\textrm{H}$) 

\begin{equation}
\textrm{H} =
\begin{bmatrix}
    \frac{1}{\sqrt{2}}      & \frac{1}{\sqrt{2}} \\
    \frac{1}{\sqrt{2}}       & \frac{-1}{\sqrt{2}}  \\
\end{bmatrix}
\end{equation}

In [17]:
H_ABC_gates=ABC_decomposition(H,1)
H_ABC_quantum_circuit = decomposed_gates_to_circuit(H_ABC_gates, num_of_qubits)
H_ABC_quantum_circuit.png

In [18]:
# Check the output
H_ABC_output = matrix_of_decomposed_gates(H_ABC_quantum_circuit)
H_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

#### Pauli X ($ \sigma_x$)

\begin{equation}
\sigma_x =
\begin{bmatrix}
    0      & 1 \\
    1       & 0  \\
\end{bmatrix}
\end{equation}


In [19]:
sigmax_ABC_gates=ABC_decomposition(sigmax,1)
sigmax_ABC_quantum_circuit = decomposed_gates_to_circuit(sigmax_ABC_gates, num_of_qubits)
sigmax_ABC_quantum_circuit.png

In [20]:
# Check the output
sigmax_ABC_output = matrix_of_decomposed_gates(sigmax_ABC_quantum_circuit)
sigmax_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

#### Pauli Y ($ \sigma_y$)

\begin{equation}
\sigma_x =
\begin{bmatrix}
    0      & -i \\
    i       & 0  \\
\end{bmatrix}
\end{equation}


In [21]:
sigmay_ABC_gates=ABC_decomposition(sigmay,1)
sigmay_ABC_quantum_circuit = decomposed_gates_to_circuit(sigmay_ABC_gates, num_of_qubits)
sigmay_ABC_quantum_circuit.png

In [22]:
# Check the output
sigmay_ABC_output = matrix_of_decomposed_gates(sigmay_ABC_quantum_circuit)
sigmay_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

#### Pauli Z ($ \sigma_z$)

\begin{equation}
\sigma_x =
\begin{bmatrix}
    1      & 0 \\
    0       & -1  \\
\end{bmatrix}
\end{equation}


In [23]:
sigmaz_ABC_gates=ABC_decomposition(sigmaz,1)
sigmaz_ABC_quantum_circuit = decomposed_gates_to_circuit(sigmaz_ABC_gates, num_of_qubits)
sigmaz_ABC_quantum_circuit.png

In [24]:
# Check the output
sigmaz_ABC_output = matrix_of_decomposed_gates(sigmaz_ABC_quantum_circuit)
sigmaz_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

#### Single-Qubit Rotation ($\textrm{S}$)

\begin{equation}
\textrm{S} =
\begin{bmatrix}
    1      & 0 \\
    0       & i  \\
\end{bmatrix}
\end{equation}

In [25]:
S_ABC_gates=ABC_decomposition(S,1)
S_ABC_quantum_circuit = decomposed_gates_to_circuit(S_ABC_gates, num_of_qubits)
S_ABC_quantum_circuit.png

In [26]:
# Check the output
S_ABC_output = matrix_of_decomposed_gates(S_ABC_quantum_circuit)
S_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+1.j 0.+0.j]
 [0.+0.j 1.+0.j]]

#### Square Root of S $\left( \textrm{T} \right)$

\begin{equation}
\textrm{S} =
\begin{bmatrix}
    1      & 0 \\
    0       & e^{\frac{i \pi}{4}}  \\
\end{bmatrix}
\end{equation}


In [27]:
T_ABC_gates=ABC_decomposition(T,1)
T_ABC_quantum_circuit = decomposed_gates_to_circuit(T_ABC_gates, num_of_qubits)
T_ABC_quantum_circuit.png

In [28]:
# Check the output
T_ABC_output = matrix_of_decomposed_gates(T_ABC_quantum_circuit)
T_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.70710678+0.70710678j  0.        +0.j        ]
 [ 0.        +0.j          0.        -1.j        ]]

#### Square Root of NOT gate $\left( \textrm{SQRTNOT} \right)$

\begin{equation}
\textrm{SQRTNOT} =
\begin{bmatrix}
    \frac{1}{\sqrt{2}}      & \frac{-i}{\sqrt{2}} \\
    \frac{-i}{\sqrt{2}}       & \frac{1}{\sqrt{2}}  \\
\end{bmatrix}
\end{equation}

In [29]:
SQRTNOT_ABC_gates=ABC_decomposition(SQRTNOT,1)
SQRTNOT_ABC_quantum_circuit = decomposed_gates_to_circuit(SQRTNOT_ABC_gates, num_of_qubits)
SQRTNOT_ABC_quantum_circuit.png

In [30]:
# Check the output
SQRTNOT_ABC_output = matrix_of_decomposed_gates(SQRTNOT_ABC_quantum_circuit)
SQRTNOT_ABC_output

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.70710678+0.j          0.        +0.70710678j]
 [ 0.        +0.70710678j -0.70710678+0.j        ]]